# Generated by Django 4.2.1 on 2024-03-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('leverage', models.IntegerField(default=0)),
                ('min_deposit', models.IntegerField(default=0)),
            ],
        ),
    ]
