# Generated by Django 4.2.1 on 2024-03-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttrading',
            name='is_number',
            field=models.BooleanField(default=True),
        ),
    ]
