# Generated by Django 4.2.1 on 2024-03-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='dm_group',
        ),
    ]
