# Generated by Django 5.0.1 on 2024-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0002_tradingaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='acoount_deposit',
            field=models.BigIntegerField(default=0),
        ),
    ]
