# Generated by Django 4.2.1 on 2024-03-28 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0003_tradingaccount_dm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='account_number',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
