# Generated by Django 4.2.4 on 2024-02-26 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0003_tradingaccount_acoount_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingaccount',
            old_name='acoount_deposit',
            new_name='account_deposit',
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
