# Generated by Django 4.2.4 on 2024-02-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0004_rename_acoount_deposit_tradingaccount_account_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(default='')),
                ('leverage', models.BigIntegerField(default=0)),
                ('min_deposit', models.BigIntegerField(default=0)),
            ],
        ),
    ]
