# Generated by Django 4.2.4 on 2024-02-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0009_alter_tradingaccount_client_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='client_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading_account_app.tradingproduct'),
        ),
    ]
