# Generated by Django 4.2.1 on 2024-03-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0017_tradingaccount_dm_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='client_group',
        ),
    ]
