# Generated by Django 4.2.1 on 2024-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0018_remove_tradingaccount_client_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttrading',
            name='leverage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttrading',
            name='min_deposit',
            field=models.IntegerField(default=0),
        ),
    ]
