# Generated by Django 4.2.4 on 2024-02-27 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0004_rename_acoount_deposit_tradingaccount_account_deposit_and_more'),
        ('partner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ib_account',
            name='account_number',
            field=models.OneToOneField(limit_choices_to={'user': django.db.models.expressions.OuterRef('user')}, on_delete=django.db.models.deletion.CASCADE, to='trading_account_app.tradingaccount'),
        ),
    ]
