# Generated by Django 4.2.4 on 2024-02-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0004_rename_acoount_deposit_tradingaccount_account_deposit_and_more'),
        ('partner_app', '0002_alter_ib_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ib_account',
            name='account_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading_account_app.tradingaccount'),
        ),
    ]
