# Generated by Django 4.2.4 on 2024-02-27 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading_account_app', '0004_rename_acoount_deposit_tradingaccount_account_deposit_and_more'),
        ('partner_app', '0003_alter_ib_account_account_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IB_Account',
            new_name='IbAccount',
        ),
    ]
