# Generated by Django 4.2.4 on 2024-02-28 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading_account_app', '0004_rename_acoount_deposit_tradingaccount_account_deposit_and_more'),
        ('partner_app', '0004_rename_ib_account_ibaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibaccount',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Referralaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading_account_app.tradingaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
