# Generated by Django 4.2.4 on 2024-02-28 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_app', '0005_ibaccount_is_confirmed_referralaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_accoung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner_app.ibaccount')),
            ],
        ),
    ]
