# Generated by Django 4.2.4 on 2024-02-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0006_iblist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iblist',
            old_name='client_accoung',
            new_name='client_account',
        ),
    ]
