# Generated by Django 4.2.4 on 2024-02-28 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0007_rename_client_accoung_iblist_client_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iblist',
            old_name='user',
            new_name='ib',
        ),
    ]
