# Generated by Django 4.2.4 on 2024-02-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0008_rename_user_iblist_ib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referralaccount',
        ),
    ]
