# Generated by Django 4.2.4 on 2024-02-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0009_delete_referralaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iblist',
            name='ib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_app.ibaccount'),
        ),
    ]
