# Generated by Django 4.2.4 on 2024-02-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0010_alter_iblist_ib'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibaccount',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
