# Generated by Django 4.2.1 on 2024-03-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_account_app', '0010_alter_tradingaccount_client_group'),
        ('partner_app', '0011_ibaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibaccount',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_account_app.tradingaccount'),
        ),
    ]
