# Generated by Django 4.2.1 on 2024-03-07 10:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0013_alter_ibaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibaccount',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.AbstractUser.get_full_name, max_length=100),
        ),
    ]
