# Generated by Django 4.2.1 on 2024-03-07 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_app', '0017_alter_ibaccount_is_ib_alter_ibaccount_is_sub_ib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibaccount',
            name='is_ib',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ibaccount',
            name='is_sub_ib',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MibAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirm', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
