# Generated by Django 4.2.4 on 2024-02-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_bankdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='swift_code',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
