# Generated by Django 4.2.4 on 2024-02-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_personaldetail_is_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='is_confirm',
        ),
    ]
